// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.baidu.bjf.remoting.protobuf.idlproxy2;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_ACTION = 0;</code>
     */
    NO_ACTION(0, 0),
    /**
     * <code>DOWNLOAD = 1;</code>
     */
    DOWNLOAD(1, 1),
    /**
     * <code>DIALING = 2;</code>
     */
    DIALING(2, 2),
    /**
     * <code>MESSAGE = 3;</code>
     */
    MESSAGE(3, 3),
    /**
     * <code>MAIL = 4;</code>
     */
    MAIL(4, 4),
    ;

    /**
     * <code>NO_ACTION = 0;</code>
     */
    public static final int NO_ACTION_VALUE = 0;
    /**
     * <code>DOWNLOAD = 1;</code>
     */
    public static final int DOWNLOAD_VALUE = 1;
    /**
     * <code>DIALING = 2;</code>
     */
    public static final int DIALING_VALUE = 2;
    /**
     * <code>MESSAGE = 3;</code>
     */
    public static final int MESSAGE_VALUE = 3;
    /**
     * <code>MAIL = 4;</code>
     */
    public static final int MAIL_VALUE = 4;


    public final int getNumber() { return value; }

    public static Action valueOf(int value) {
      switch (value) {
        case 0: return NO_ACTION;
        case 1: return DOWNLOAD;
        case 2: return DIALING;
        case 3: return MESSAGE;
        case 4: return MAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Action(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Action)
  }

  public interface EntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string str = 1;
    /**
     * <code>required string str = 1;</code>
     */
    boolean hasStr();
    /**
     * <code>required string str = 1;</code>
     */
    java.lang.String getStr();
    /**
     * <code>required string str = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();

    // repeated string key = 2;
    /**
     * <code>repeated string key = 2;</code>
     */
    java.util.List<java.lang.String>
    getKeyList();
    /**
     * <code>repeated string key = 2;</code>
     */
    int getKeyCount();
    /**
     * <code>repeated string key = 2;</code>
     */
    java.lang.String getKey(int index);
    /**
     * <code>repeated string key = 2;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes(int index);
  }
  /**
   * Protobuf type {@code Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage
      implements EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }

    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              str_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                key_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              key_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          key_ = new com.google.protobuf.UnmodifiableLazyStringList(key_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Entry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.class, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder.class);
    }

    public static com.google.protobuf.Parser<Entry> PARSER =
        new com.google.protobuf.AbstractParser<Entry>() {
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string str = 1;
    public static final int STR_FIELD_NUMBER = 1;
    private java.lang.Object str_;
    /**
     * <code>required string str = 1;</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string str = 1;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string key = 2;
    public static final int KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList key_;
    /**
     * <code>repeated string key = 2;</code>
     */
    public java.util.List<java.lang.String>
        getKeyList() {
      return key_;
    }
    /**
     * <code>repeated string key = 2;</code>
     */
    public int getKeyCount() {
      return key_.size();
    }
    /**
     * <code>repeated string key = 2;</code>
     */
    public java.lang.String getKey(int index) {
      return key_.get(index);
    }
    /**
     * <code>repeated string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes(int index) {
      return key_.getByteString(index);
    }

    private void initFields() {
      str_ = "";
      key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrBytes());
      }
      for (int i = 0; i < key_.size(); i++) {
        output.writeBytes(2, key_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < key_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(key_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getKeyList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.class, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder.class);
      }

      // Construct using com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Entry_descriptor;
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry getDefaultInstanceForType() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.getDefaultInstance();
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry build() {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry buildPartial() {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry result = new com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.str_ = str_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          key_ = new com.google.protobuf.UnmodifiableLazyStringList(
              key_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry) {
          return mergeFrom((com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry other) {
        if (other == com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.getDefaultInstance()) return this;
        if (other.hasStr()) {
          bitField0_ |= 0x00000001;
          str_ = other.str_;
          onChanged();
        }
        if (!other.key_.isEmpty()) {
          if (key_.isEmpty()) {
            key_ = other.key_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeyIsMutable();
            key_.addAll(other.key_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string str = 1;
      private java.lang.Object str_ = "";
      /**
       * <code>required string str = 1;</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string str = 1;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          str_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        str_ = value;
        onChanged();
        return this;
      }

      // repeated string key = 2;
      private com.google.protobuf.LazyStringList key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          key_ = new com.google.protobuf.LazyStringArrayList(key_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public java.util.List<java.lang.String>
          getKeyList() {
        return java.util.Collections.unmodifiableList(key_);
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public int getKeyCount() {
        return key_.size();
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public java.lang.String getKey(int index) {
        return key_.get(index);
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes(int index) {
        return key_.getByteString(index);
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public Builder setKey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public Builder addKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public Builder addAllKey(
          java.lang.Iterable<java.lang.String> values) {
        ensureKeyIsMutable();
        super.addAll(values, key_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public Builder clearKey() {
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 2;</code>
       */
      public Builder addKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Entry)
    }

    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Entry)
  }

  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 ival = 1;
    /**
     * <code>optional int32 ival = 1;</code>
     */
    boolean hasIval();
    /**
     * <code>optional int32 ival = 1;</code>
     */
    int getIval();

    // optional string sval = 2;
    /**
     * <code>optional string sval = 2;</code>
     */
    boolean hasSval();
    /**
     * <code>optional string sval = 2;</code>
     */
    java.lang.String getSval();
    /**
     * <code>optional string sval = 2;</code>
     */
    com.google.protobuf.ByteString
        getSvalBytes();

    // repeated .Entry entry = 3;
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> 
        getEntryList();
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry getEntry(int index);
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    java.util.List<? extends com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder> 
        getEntryOrBuilderList();
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder getEntryOrBuilder(
        int index);

    // optional .Action action = 4;
    /**
     * <code>optional .Action action = 4;</code>
     */
    boolean hasAction();
    /**
     * <code>optional .Action action = 4;</code>
     */
    com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action getAction();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ival_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sval_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                entry_ = new java.util.ArrayList<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry>();
                mutable_bitField0_ |= 0x00000004;
              }
              entry_.add(input.readMessage(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action value = com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                action_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.class, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 ival = 1;
    public static final int IVAL_FIELD_NUMBER = 1;
    private int ival_;
    /**
     * <code>optional int32 ival = 1;</code>
     */
    public boolean hasIval() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 ival = 1;</code>
     */
    public int getIval() {
      return ival_;
    }

    // optional string sval = 2;
    public static final int SVAL_FIELD_NUMBER = 2;
    private java.lang.Object sval_;
    /**
     * <code>optional string sval = 2;</code>
     */
    public boolean hasSval() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sval = 2;</code>
     */
    public java.lang.String getSval() {
      java.lang.Object ref = sval_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sval_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sval = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSvalBytes() {
      java.lang.Object ref = sval_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Entry entry = 3;
    public static final int ENTRY_FIELD_NUMBER = 3;
    private java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> entry_;
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    public java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    public java.util.List<? extends com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .Entry entry = 3;</code>
     */
    public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    // optional .Action action = 4;
    public static final int ACTION_FIELD_NUMBER = 4;
    private com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action action_;
    /**
     * <code>optional .Action action = 4;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Action action = 4;</code>
     */
    public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action getAction() {
      return action_;
    }

    private void initFields() {
      ival_ = 0;
      sval_ = "";
      entry_ = java.util.Collections.emptyList();
      action_ = com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action.NO_ACTION;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ival_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSvalBytes());
      }
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(3, entry_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, action_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ival_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSvalBytes());
      }
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, entry_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, action_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.class, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.Builder.class);
      }

      // Construct using com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ival_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sval_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          entryBuilder_.clear();
        }
        action_ = com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action.NO_ACTION;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.internal_static_Msg_descriptor;
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg getDefaultInstanceForType() {
        return com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.getDefaultInstance();
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg build() {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg buildPartial() {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg result = new com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ival_ = ival_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sval_ = sval_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.action_ = action_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg) {
          return mergeFrom((com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg other) {
        if (other == com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg.getDefaultInstance()) return this;
        if (other.hasIval()) {
          setIval(other.getIval());
        }
        if (other.hasSval()) {
          bitField0_ |= 0x00000002;
          sval_ = other.sval_;
          onChanged();
        }
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000004);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 ival = 1;
      private int ival_ ;
      /**
       * <code>optional int32 ival = 1;</code>
       */
      public boolean hasIval() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 ival = 1;</code>
       */
      public int getIval() {
        return ival_;
      }
      /**
       * <code>optional int32 ival = 1;</code>
       */
      public Builder setIval(int value) {
        bitField0_ |= 0x00000001;
        ival_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ival = 1;</code>
       */
      public Builder clearIval() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ival_ = 0;
        onChanged();
        return this;
      }

      // optional string sval = 2;
      private java.lang.Object sval_ = "";
      /**
       * <code>optional string sval = 2;</code>
       */
      public boolean hasSval() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sval = 2;</code>
       */
      public java.lang.String getSval() {
        java.lang.Object ref = sval_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sval_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sval = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSvalBytes() {
        java.lang.Object ref = sval_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sval_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sval = 2;</code>
       */
      public Builder setSval(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sval = 2;</code>
       */
      public Builder clearSval() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sval_ = getDefaultInstance().getSval();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sval = 2;</code>
       */
      public Builder setSvalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sval_ = value;
        onChanged();
        return this;
      }

      // repeated .Entry entry = 3;
      private java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          entry_ = new java.util.ArrayList<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry>(entry_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder setEntry(
          int index, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder setEntry(
          int index, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder addEntry(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder addEntry(
          int index, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder addEntry(
          com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder addEntry(
          int index, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder addAllEntry(
          java.lang.Iterable<? extends com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          super.addAll(values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public java.util.List<? extends com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .Entry entry = 3;</code>
       */
      public java.util.List<com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Entry.Builder, com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.EntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // optional .Action action = 4;
      private com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action action_ = com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action.NO_ACTION;
      /**
       * <code>optional .Action action = 4;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Action action = 4;</code>
       */
      public com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action getAction() {
        return action_;
      }
      /**
       * <code>optional .Action action = 4;</code>
       */
      public Builder setAction(com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Action action = 4;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        action_ = com.baidu.bjf.remoting.protobuf.idlproxy2.TestProtos.Action.NO_ACTION;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\"!\n\005Entry\022\013\n\003str\030\001 \002(\t\022\013\n\003ke" +
      "y\030\002 \003(\t\"Q\n\003Msg\022\014\n\004ival\030\001 \001(\005\022\014\n\004sval\030\002 \001" +
      "(\t\022\025\n\005entry\030\003 \003(\0132\006.Entry\022\027\n\006action\030\004 \001(" +
      "\0162\007.Action*I\n\006Action\022\r\n\tNO_ACTION\020\000\022\014\n\010D" +
      "OWNLOAD\020\001\022\013\n\007DIALING\020\002\022\013\n\007MESSAGE\020\003\022\010\n\004M" +
      "AIL\020\004B7\n)com.baidu.bjf.remoting.protobuf" +
      ".idlproxy2B\nTestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Entry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Entry_descriptor,
              new java.lang.String[] { "Str", "Key", });
          internal_static_Msg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_descriptor,
              new java.lang.String[] { "Ival", "Sval", "Entry", "Action", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
